#!bin/bash
e='echo -e ' && r='read -r ' && b='bash ' && p='echo -e  |P|: ' && re='echo -e  |R|: ' && bar='echo -e  |═══════════════════════════════════════════|' && separador="◣◥◣◥◤◢◤◢◣◥◣◥◤◢◤◢◣◥◣◥◤◢◤◢◣◥◣◥◤◢◤◢◣◥◣◥◤◢◤◢"
negro=' [1;30m' && azul=' [1;34m' && verde=' [1;32m' && cian=' [1;36m' && rojo=' [1;31m' && purpura=' [1;35m'  && amarillo=' [1;33m'  && blanco=' [1;37m'  && black=' [0;30m' && blue=' [0;34m' && green=' [0;32m' && cyan=' [0;36m'  && red=' [0;31m'  && purple=' [0;35m'  && yellow=' [0;33m'  && white=' [0;37m' && linea="echo -e ${rojo} ————————————————————————————————————————————————————————————————————" sn="\033[0;m" && SN="\e[0;m" && PWD=$(pwd)
#################################
#	B A N N E R S		#
#################################
banner_johan(){
$linea
$e "\033[0;m
███████████                      █████                        ██████   ██████
░░███░░░░░███                    ░░███                        ░░██████ ██████
 ░███    ░███ ████████   ██████  ███████    ██████             ░███░█████░███
 ░██████████ ░░███░░███ ███░░███░░░███░    ███░░███ ██████████ ░███░░███ ░███
 ░███░░░░░░   ░███ ░░░ ░███ ░███  ░███    ░███ ░███░░░░░░░░░░  ░███ ░░░  ░███
 ░███         ░███     ░███ ░███  ░███ ███░███ ░███            ░███      ░███
 █████        █████    ░░██████   ░░█████ ░░██████             █████     █████
░░░░░        ░░░░░      ░░░░░░     ░░░░░   ░░░░░░             ░░░░░     ░░░░░
"
$linea
}
banner_drowkid(){
$linea
$e "
	      ${cian}███████╗██████╗  █████╗  ██████╗███████╗
	      ${cyan}██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝
	      ${purpura}███████╗██████╔╝███████║██║     █████╗
	      ${purple}╚════██║██╔═══╝ ██╔══██║██║     ██╔══╝
	      ${amarillo}███████║██║     ██║  ██║╚██████╗███████╗
	      ${verde}╚══════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝╚══════╝
   ${cian}███╗   ██╗███████╗████████╗██╗    ██╗ ██████╗ ██████╗ ██╗  ██╗
   ${cyan}████╗  ██║██╔════╝╚══██╔══╝██║    ██║██╔═══██╗██╔══██╗██║ ██╔╝
   ${purpura}██╔██╗ ██║█████╗     ██║   ██║ █╗ ██║██║   ██║██████╔╝█████╔╝
   ${purple}██║╚██╗██║██╔══╝     ██║   ██║███╗██║██║   ██║██╔══██╗██╔═██╗
   ${amarillo}██║ ╚████║███████╗   ██║   ╚███╔███╔╝╚██████╔╝██║  ██║██║  ██╗
   ${yellow}╚═╝  ╚═══╝╚══════╝   ╚═╝    ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
"
$linea
}
#########################
#	N A M E S 	#
#########################
tit_spnw() { $linea && $e "" && $e " 	           \033[1;97m🚀 |\e[33mＳｐａｃｅＮｅｔｗｏｒｋ\e[0;m| 🚀         " && $e "" && $linea ; }
tit_proto(){ $linea  &&  $e ""  && $e " 	           \033[1;97m🌐 |\e[33mＰｒｏｔｏ－Ｍａｎａｇｅｒ\e[0;m| 🌐         " && $e "" && $linea ; }
####################################################################################
#	K E Y S 	#	K E Y S 	 #	K E Y S		  ##########
####################################################################################
verificar_key(){ 
$e "Aun en desarrollo"
#$e "${amarillo}ingrese su key: " && wget $IPC/.key && source ${PWD}/.key && $r key && PWD=$(pwd)
#if [[ "${key}" == "$form" || "${key}" == "${form}" ]]; then
#        $e "\e[0;mVerificando key.." && sleep 3 && $e "${verde}[✓]Key válida.[✓]" &&        $e "+REGISTRANDO SU IP EN LA BASE DE DATOS+" &&        rm .key.log &&        banner_drowkid;clear
#elif [[ "${key}" == "-" || "${key}" == "${nk}" ]]; then  
#        $e "error"
#else 
#        $e "Error"
#fi
}
ofus () {
unset key
key=$(ofus "$code|olal")
unset IPC
IPC="34.86.137.169:2588/"
unset code
code=$(openssl rand -base64 16)
unset server
server=$(echo ${txt_ofuscatw}|cut -d':' -f1)
unset txtofus
number=$(expr length $1)
for((i=1; i<$number+1; i++)); do
txt[$i]=$(echo "$1" | cut -b $i)
case ${txt[$i]} in
"&")txt[$i]="+";;
"+")txt[$i]=".";;
"1")txt[$i]="@";;
"@")txt[$i]="1";;
"2")txt[$i]="?";;
"?")txt[$i]="2";;
"4")txt[$i]="%";;
"%")txt[$i]="4";;
"-")txt[$i]="K";;
"K")txt[$i]="-";;
esac
txtofus+="${txt[$i]}"
done
echo "$txtofus" | rev
}
genk() { name="olal-dik" && $e "$key" && $e "$key">.key; }
#################################
#	U P D A T E S 		#
#################################
space(){ wget https://raw.githubusercontent.com/drowkid-1/SpaceNetwork/main/Install/SpaceNW.sh && chmod 777 SpaceNW.sh;./SpaceNW.sh ; }
proto(){ wget https://raw.githubusercontent.com/drowkid-1/SpaceNetwork/main/Install/Proto-Manager.sh && chmod 777 Proto-Manager.sh ; }
#################################
#	H E L P - A D M I N	#
#################################
help_admin(){
$e $verde "Welcome admin!\033[0;m
usage general:

$yellow   --generar-key\033[0;m | Genera keys para la instalación de ambos scripts.

usage in${verde}Ｐｒｏｔｏ－Ｍａｎａｇｅｒ:\e[0;m

$yellow   --title-proto $sn| Muestra y utiliza el título de Proto-Manager.
$yellow   --admin-proto $sn| Muestra el menú de ayuda para admins.
$yellow  --banner-johan $sn| Muestra y utiliza el banner de Proto-Manager.
$yellow  --update-proto $sn| Actualiza el repositorio automaticamente.

usage in${verde}ＳｐａｃｅＮｅｔｗｏｒｋ:\033[0;m

$yellow--banner-drowkid $sn| Muestra y utiliza el banner de SpaceNetwork.
$yellow   --admin-space $sn| Muestra el menú de ayuda para admins.
$yellow  --update-space $sn| Actualiza el repositorio autómaticamente.
$yellow   --title-space $sn| Muestra y utiliza el título de SpaceNetwork.
"
}
#########################
#	 M E N U 	#
#########################

while :; do
  case $1 in
  --banner-drowkid | --banner-drowk | --banner-dk)
    banner_drowkid 
    break
     ;;
  --banner-johan | --banner-jhn | --bj)
    banner_johan
    break
    ;;
  --generar-key | --gen-k)
    genk
    break
    ;;
  -k | --ofus-key)
    verificar_key
    break
    ;;
  --help-space | --help-admin | --help-vip | --help-proto | --help-johan | --help-drowkid)
    help_admin
    break
    ;;
  --update-space | --Install-space)
    space
    break
    ;;
  --update-proto | --update-proto)
    proto
    break
    ;;
  --title-space)
    tit_spnw
    break
    ;;
  --title-proto)
    tit_proto
    break
    ;;
  --adminSN-panel | --admin-space | --admin-panel-sn)
    spaceADM_inst
    break
    ;;
  --adminPM-panel | --admin-proto)
    proto
    break
    ;;
  --title-proto)
    tit_proto
    break
    ;;
  *) exit ;;
  esac
done


